name = "SignPlus"
version = "1.3"
description = "SignPlus v"..version.."\n allows to edit and show custom text on signs and chests"
author = "Rincewind"
forumthread = "N/A"
api_version = 6
icon_atlas = "preview.xml"
icon = "preview.tex"
dont_starve_compatible = true
reign_of_giants_compatible = true